### ISSUE TITLE
Perform various GitHub repo chores

### ISSUE THREAD

**Issue by c10k-cc** [barter-rs/barter-rs#10]
# Perform various _GitHub_ repo chores

## Summary

This issue / proposal addresses various miscellaneous tasks related to _GitHub_ repo which need to be performed.

## Description

These are some of the tasks which need to be performed (on all 4 repos):
* [x] add project description
* [x] add project topics / keywords
  * look at other similar trading bots, libs & frameworks and copy keywords from them
* [x] add project URL
  * use organisation repos page
* [ ] configure _GitHub Actions_ file
  * add testing pipeline
  * add linting / re-formatting pipeline
  * additions??
* [ ] add `PULL_REQUEST_TEMPLATE` file
* [ ] add `ISSUE_TEMPLATE` file
* [ ] add other common files
  * take a look here: https://stackoverflow.com/questions/60507097
  * and here: https://keepachangelog.com/
  * and also here: https://github.com/kmindi/special-files-in-repository-root/blob/master/README.md
  * (semi-unrelated) here also: https://github.com/vweevers/common-changelog
